[2024-11-05 16:27:00 +0700] [2583760] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:27:00 +0700] [2583760] [INFO] Listening at: http://0.0.0.0:8000 (2583760)
[2024-11-05 16:27:00 +0700] [2583760] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 16:27:00 +0700] [2583796] [INFO] Booting worker with pid: 2583796
[2024-11-05 16:27:00 +0700] [2583815] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:27:00 +0700] [2583796] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 16:27:00 +0700] [2583796] [INFO] Worker exiting (pid: 2583796)
[2024-11-05 16:27:00 +0700] [2583760] [ERROR] Worker (pid:2583796) exited with code 3
[2024-11-05 16:27:00 +0700] [2583760] [ERROR] Shutting down: Master
[2024-11-05 16:27:00 +0700] [2583760] [ERROR] Reason: Worker failed to boot.
[2024-11-05 16:27:01 +0700] [2584278] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:27:01 +0700] [2584278] [INFO] Listening at: http://0.0.0.0:8000 (2584278)
[2024-11-05 16:27:01 +0700] [2584278] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 16:27:01 +0700] [2584310] [INFO] Booting worker with pid: 2584310
[2024-11-05 16:27:01 +0700] [2584310] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 16:27:01 +0700] [2584310] [INFO] Worker exiting (pid: 2584310)
[2024-11-05 16:27:01 +0700] [2584278] [ERROR] Worker (pid:2584310) exited with code 3
[2024-11-05 16:27:01 +0700] [2584278] [ERROR] Shutting down: Master
[2024-11-05 16:27:01 +0700] [2584278] [ERROR] Reason: Worker failed to boot.
[2024-11-05 16:29:57 +0700] [2652265] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:29:57 +0700] [2652265] [INFO] Listening at: http://0.0.0.0:8000 (2652265)
[2024-11-05 16:29:57 +0700] [2652265] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 16:29:57 +0700] [2652305] [INFO] Booting worker with pid: 2652305
[2024-11-05 16:29:58 +0700] [2652314] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:29:58 +0700] [2652305] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 16:29:58 +0700] [2652305] [INFO] Worker exiting (pid: 2652305)
[2024-11-05 16:29:58 +0700] [2652265] [ERROR] Worker (pid:2652305) exited with code 3
[2024-11-05 16:29:58 +0700] [2652265] [ERROR] Shutting down: Master
[2024-11-05 16:29:58 +0700] [2652265] [ERROR] Reason: Worker failed to boot.
[2024-11-05 16:29:59 +0700] [2652768] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:29:59 +0700] [2652768] [INFO] Listening at: http://0.0.0.0:8000 (2652768)
[2024-11-05 16:29:59 +0700] [2652768] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 16:29:59 +0700] [2652811] [INFO] Booting worker with pid: 2652811
[2024-11-05 16:29:59 +0700] [2652811] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 16:29:59 +0700] [2652811] [INFO] Worker exiting (pid: 2652811)
[2024-11-05 16:29:59 +0700] [2652768] [ERROR] Worker (pid:2652811) exited with code 3
[2024-11-05 16:29:59 +0700] [2652768] [ERROR] Shutting down: Master
[2024-11-05 16:29:59 +0700] [2652768] [ERROR] Reason: Worker failed to boot.
[2024-11-05 16:54:16 +0700] [3217825] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:54:16 +0700] [3217825] [INFO] Listening at: http://0.0.0.0:8000 (3217825)
[2024-11-05 16:54:16 +0700] [3217825] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 16:54:16 +0700] [3217870] [INFO] Booting worker with pid: 3217870
[2024-11-05 16:54:16 +0700] [3217874] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:54:16 +0700] [3217870] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 16:54:16 +0700] [3217870] [INFO] Worker exiting (pid: 3217870)
[2024-11-05 16:54:16 +0700] [3217825] [ERROR] Worker (pid:3217870) exited with code 3
[2024-11-05 16:54:16 +0700] [3217825] [ERROR] Shutting down: Master
[2024-11-05 16:54:16 +0700] [3217825] [ERROR] Reason: Worker failed to boot.
[2024-11-05 16:54:17 +0700] [3218340] [INFO] Starting gunicorn 23.0.0
[2024-11-05 16:54:17 +0700] [3218340] [INFO] Listening at: http://0.0.0.0:8000 (3218340)
[2024-11-05 16:54:17 +0700] [3218340] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 16:54:17 +0700] [3218383] [INFO] Booting worker with pid: 3218383
[2024-11-05 16:54:17 +0700] [3218383] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 16:54:17 +0700] [3218383] [INFO] Worker exiting (pid: 3218383)
[2024-11-05 16:54:17 +0700] [3218340] [ERROR] Worker (pid:3218383) exited with code 3
[2024-11-05 16:54:17 +0700] [3218340] [ERROR] Shutting down: Master
[2024-11-05 16:54:17 +0700] [3218340] [ERROR] Reason: Worker failed to boot.
[2024-11-05 17:00:11 +0700] [3355623] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:00:11 +0700] [3355623] [INFO] Listening at: http://0.0.0.0:8000 (3355623)
[2024-11-05 17:00:11 +0700] [3355623] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 17:00:11 +0700] [3355654] [INFO] Booting worker with pid: 3355654
[2024-11-05 17:00:11 +0700] [3355684] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:00:11 +0700] [3355654] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 17:00:11 +0700] [3355654] [INFO] Worker exiting (pid: 3355654)
[2024-11-05 17:00:11 +0700] [3355623] [ERROR] Worker (pid:3355654) exited with code 3
[2024-11-05 17:00:11 +0700] [3355623] [ERROR] Shutting down: Master
[2024-11-05 17:00:11 +0700] [3355623] [ERROR] Reason: Worker failed to boot.
[2024-11-05 17:00:12 +0700] [3356129] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:00:12 +0700] [3356129] [INFO] Listening at: http://0.0.0.0:8000 (3356129)
[2024-11-05 17:00:12 +0700] [3356129] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 17:00:12 +0700] [3356160] [INFO] Booting worker with pid: 3356160
[2024-11-05 17:00:12 +0700] [3356160] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 17:00:12 +0700] [3356160] [INFO] Worker exiting (pid: 3356160)
[2024-11-05 17:00:12 +0700] [3356129] [ERROR] Worker (pid:3356160) exited with code 3
[2024-11-05 17:00:12 +0700] [3356129] [ERROR] Shutting down: Master
[2024-11-05 17:00:12 +0700] [3356129] [ERROR] Reason: Worker failed to boot.
[2024-11-05 17:10:15 +0700] [3590650] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:10:15 +0700] [3590650] [INFO] Listening at: http://0.0.0.0:8000 (3590650)
[2024-11-05 17:10:15 +0700] [3590650] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 17:10:15 +0700] [3590687] [INFO] Booting worker with pid: 3590687
[2024-11-05 17:10:15 +0700] [3590695] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:10:15 +0700] [3590687] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 17:10:15 +0700] [3590687] [INFO] Worker exiting (pid: 3590687)
[2024-11-05 17:10:15 +0700] [3590650] [ERROR] Worker (pid:3590687) exited with code 3
[2024-11-05 17:10:15 +0700] [3590650] [ERROR] Shutting down: Master
[2024-11-05 17:10:15 +0700] [3590650] [ERROR] Reason: Worker failed to boot.
[2024-11-05 17:10:16 +0700] [3591157] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:10:16 +0700] [3591157] [INFO] Listening at: http://0.0.0.0:8000 (3591157)
[2024-11-05 17:10:16 +0700] [3591157] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 17:10:16 +0700] [3591199] [INFO] Booting worker with pid: 3591199
[2024-11-05 17:10:16 +0700] [3591199] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-11-05 17:10:16 +0700] [3591199] [INFO] Worker exiting (pid: 3591199)
[2024-11-05 17:10:16 +0700] [3591157] [ERROR] Worker (pid:3591199) exited with code 3
[2024-11-05 17:10:16 +0700] [3591157] [ERROR] Shutting down: Master
[2024-11-05 17:10:16 +0700] [3591157] [ERROR] Reason: Worker failed to boot.
[2024-11-05 17:41:37 +0700] [131227] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:41:37 +0700] [131227] [INFO] Listening at: http://0.0.0.0:8000 (131227)
[2024-11-05 17:41:37 +0700] [131227] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 17:41:37 +0700] [131272] [INFO] Booting worker with pid: 131272
[2024-11-05 17:41:37 +0700] [131277] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:41:37 +0700] [131272] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wwwroot'
[2024-11-05 17:41:37 +0700] [131272] [INFO] Worker exiting (pid: 131272)
[2024-11-05 17:41:37 +0700] [131227] [ERROR] Worker (pid:131272) exited with code 3
[2024-11-05 17:41:37 +0700] [131227] [ERROR] Shutting down: Master
[2024-11-05 17:41:37 +0700] [131227] [ERROR] Reason: Worker failed to boot.
[2024-11-05 17:41:38 +0700] [131749] [INFO] Starting gunicorn 23.0.0
[2024-11-05 17:41:38 +0700] [131749] [INFO] Listening at: http://0.0.0.0:8000 (131749)
[2024-11-05 17:41:38 +0700] [131749] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-11-05 17:41:38 +0700] [131785] [INFO] Booting worker with pid: 131785
[2024-11-05 17:41:38 +0700] [131785] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/www/wwwroot/F5/backend/3712a6de97f1df1f97a9f391a104311b_venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wwwroot'
[2024-11-05 17:41:38 +0700] [131785] [INFO] Worker exiting (pid: 131785)
[2024-11-05 17:41:38 +0700] [131749] [ERROR] Worker (pid:131785) exited with code 3
[2024-11-05 17:41:38 +0700] [131749] [ERROR] Shutting down: Master
[2024-11-05 17:41:38 +0700] [131749] [ERROR] Reason: Worker failed to boot.
